# Generated by Django 4.1.2 on 2023-04-02 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='Phone',
            new_name='phone',
        ),
    ]
