# Generated by Django 4.1.2 on 2023-04-02 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_phone_useraccount_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='phone',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
