# Generated by Django 4.1.2 on 2023-04-02 20:10

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_useraccount_phone_useraccount_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=17, region=None, unique=True),
        ),
    ]
