# Generated by Django 4.1.2 on 2023-04-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_useraccount_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
