# Generated by Django 4.1.2 on 2023-04-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_blog_wordcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='audience',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_ideas',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
