# Generated by Django 4.1.2 on 2023-04-13 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_blogideasave'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='BlogIdea',
        ),
    ]
