# Generated by Django 4.1.2 on 2023-04-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_blogsection_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsection',
            name='wordCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
