# Generated by Django 4.1.2 on 2023-04-14 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_story'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Story',
            new_name='StoryDetails',
        ),
    ]
