# Generated by Django 4.1.2 on 2023-04-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_story_storydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storydetails',
            name='story',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
