# Generated by Django 4.1.2 on 2023-04-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_storydetails_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='wordCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
