# Generated by Django 4.1.2 on 2023-04-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_useraccount_wordcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='premium',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='subscription',
            field=models.CharField(blank=True, default='Free Trail', max_length=150, null=True),
        ),
    ]
