# Generated by Django 4.1.2 on 2023-04-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_useraccount_premium_useraccount_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='subscription',
            new_name='subscriptionType',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='monthlyCount',
            field=models.IntegerField(default=20000),
        ),
    ]
