# Generated by Django 4.1.2 on 2023-04-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='BlogCollection',
        ),
    ]
