# Generated by Django 4.1.2 on 2023-04-14 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_blog_blogcollection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogCollection',
            new_name='BlogCollectionDetails',
        ),
    ]
