# Generated by Django 4.1.2 on 2023-04-14 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_rename_blogcollection_blogcollectiondetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogCollectionDetails',
            new_name='BlogCollection',
        ),
    ]
