# Generated by Django 4.1.2 on 2023-04-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_rename_blogcollectiondetails_blogcollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcollection',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
