# Generated by Django 4.1.2 on 2023-04-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_blogcollection_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcollection',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
