# Generated by Django 4.1.2 on 2023-04-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_useraccount_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcollection',
            name='wordCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blogidea',
            name='wordCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='wordCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='storydetails',
            name='wordCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
