# Generated by Django 4.1.2 on 2023-04-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_blogcollection_wordcount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogideasave',
            name='wordCount',
            field=models.IntegerField(default=0),
        ),
    ]
