# Generated by Django 4.1.2 on 2023-04-14 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_blogideasave_wordcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.IntegerField(default=20000)),
                ('month', models.IntegerField(default=1)),
                ('prize', models.FloatField(default=25.9)),
            ],
        ),
        migrations.CreateModel(
            name='BeginnerLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.IntegerField(default=20000)),
                ('month', models.IntegerField(default=1)),
                ('prize', models.FloatField(default=10.0)),
            ],
        ),
        migrations.CreateModel(
            name='FreeTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.IntegerField(default=20000)),
                ('month', models.IntegerField(default=1)),
                ('prize', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advanced_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.advancedlevel')),
                ('beginner_lever', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.beginnerlevel')),
                ('freeTrail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.freetrail')),
            ],
        ),
    ]
