# Generated by Django 4.1.2 on 2023-04-14 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_advancedlevel_beginnerlevel_freetrail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumsubscription',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
