# Generated by Django 4.1.2 on 2023-04-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_premiumsubscription_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.IntegerField(default=20000)),
                ('month', models.IntegerField(default=1)),
                ('prize', models.FloatField(default=25.9)),
            ],
        ),
    ]
