# Generated by Django 4.1.2 on 2023-04-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_prime'),
    ]

    operations = [
        migrations.AddField(
            model_name='prime',
            name='prime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
