# Generated by Django 4.1.2 on 2023-04-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_prime_prime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prime',
            name='prize',
            field=models.FloatField(default=0.0),
        ),
    ]
