# Generated by Django 4.1.2 on 2023-04-15 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_prime_prize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumsubscription',
            name='advanced_level',
        ),
        migrations.RemoveField(
            model_name='premiumsubscription',
            name='beginner_lever',
        ),
        migrations.AddField(
            model_name='premiumsubscription',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='premiumsubscription',
            name='payment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='premiumsubscription',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='premiumsubscription',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prime',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='premiumsubscription',
            name='freeTrail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.prime'),
        ),
        migrations.DeleteModel(
            name='AdvancedLevel',
        ),
        migrations.DeleteModel(
            name='BeginnerLevel',
        ),
        migrations.DeleteModel(
            name='FreeTrail',
        ),
    ]
