# Generated by Django 4.1.2 on 2023-04-15 12:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_remove_premiumsubscription_advanced_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=10, region=None, unique=True)),
                ('otp', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
