# Generated by Django 4.1.2 on 2023-04-16 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_remove_otp_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premiumsubscription',
            old_name='freeTrail',
            new_name='plan',
        ),
    ]
