# Generated by Django 4.1.2 on 2023-04-17 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_currentsub'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentsub',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.prime'),
            preserve_default=False,
        ),
    ]
