# Generated by Django 4.1.2 on 2023-04-17 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_currentsub_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentsub',
            name='plan',
        ),
    ]
