# Generated by Django 4.1.2 on 2023-04-24 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_remove_currentsub_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogideasave',
            name='idea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.blogidea'),
            preserve_default=False,
        ),
    ]
