# Generated by Django 4.1.2 on 2023-04-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_blogideasave_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogideasave',
            name='idea_key',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
