# Generated by Django 4.1.2 on 2023-04-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_blogideasave_idea_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcollection',
            name='blog',
            field=models.CharField(blank=True, max_length=1300, null=True),
        ),
    ]
