# Generated by Django 4.1.2 on 2023-04-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_alter_blogcollection_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcollection',
            name='blog',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
