# Generated by Django 4.1.2 on 2023-04-25 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_otp_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
    ]
