# Generated by Django 4.1.2 on 2023-04-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_remove_otp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumsubscription',
            name='planName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
