# Generated by Django 4.1.2 on 2023-04-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_premiumsubscription_planname'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumsubscription',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
