# Generated by Django 4.1.2 on 2023-04-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_premiumsubscription_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumsubscription',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='premiumsubscription',
            name='words',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
