# Generated by Django 4.1.2 on 2023-04-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_premiumsubscription_status_premiumsubscription_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='email_verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
